/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries


-- Find total customers by gender


-- Find total products by category


-- What is the average costs in each category?


-- What is the total revenue generated for each category?



-- What is the total revenue generated by each customer?


-- What is the distribution of sold items across countries?
