/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

USE datawarehouse_analytics;


-- Find total customers by countries
SELECT country, COUNT(*) AS customers_count FROM dim_customers GROUP BY country ORDER BY customers_count DESC;


-- Find total customers by gender
SELECT gender, COUNT(*) AS customers_count FROM dim_customers GROUP BY gender ORDER BY customers_count DESC;


-- Find total products by category
SELECT category, COUNT(*) AS products_count FROM dim_products GROUP BY category ORDER BY products_count DESC;


-- What is the average costs in each category?
SELECT category, ROUND(AVG(cost), 2) AS avg_product_cost FROM dim_products GROUP BY category ORDER BY avg_product_cost DESC;


-- What is the total revenue generated for each category?
SELECT dp.category, SUM(fs.sales_amount) AS total_revenue FROM fact_sales fs  
LEFT JOIN dim_products dp ON dp.product_key=fs.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;


-- What is the total revenue generated by each customer?
SELECT dc.customer_key, dc.first_name, dc.last_name, SUM(fs.sales_amount) AS total_revenue FROM fact_sales fs  
LEFT JOIN dim_customers dc ON dc.customer_key=fs.customer_key
GROUP BY dc.first_name, dc.last_name, dc.customer_key
ORDER BY total_revenue DESC;


-- What is the distribution of sold items across countries?
SELECT dc.country, SUM(fs.quantity) AS total_items_sold FROM dim_customers dc 
LEFT JOIN fact_sales fs ON fs.customer_key=dc.customer_key
GROUP BY dc.country 
ORDER BY total_items_sold DESC;
